### ISSUE TITLE
Error 10038 and sometimes crashes at if(!isOpen)

### ISSUE THREAD

**Issue by ShahJugalR** [Jaysmito101/jmnet#2]
Facing above mentioned error and tried with default 122.0.0.1 as well as with another machine. used the code provided in the documentation only but facing error

**Comment by Jaysmito101** [comment]
@ShahJugalR what's code are you trying to run? And what are the outputs? What are the error message if any??

**Comment by Jaysmito101** [comment]
@ShahJugalR Error 10038 means we are trying to do a operation on something that's not a socket. But that's not something that should occur ar the line you are mentioning so could you please provide more details about what code you are trying to run.😁

**Comment by ShahJugalR** [comment]
I took the example folder's code made a new project in VS2022 and added all three files header and 2 cpps first i removed the client cpp from project and built an exe. Then added client one and removed server made another exe. And then after doing this started server then client. 

(I deleted that website in create server so it can create a local server in 122.0.0.1 which was default input.

**Comment by ShahJugalR** [comment]
![image](https://user-images.githubusercontent.com/61039228/147972596-7e8cfebb-1929-4e80-95d4-0bb1bce424c6.jpeg)

**Comment by Jaysmito101** [comment]
@ShahJugalR change 122.0.0.1 to 127.0.0.1

**Comment by ShahJugalR** [comment]
Yes it is made a typing mistake its the default address which was in function declaration. I used 127.0.0.1 only. 


Thanks for helping. Its hard to find support from repository authors but you replied thats great👍.

**Comment by Jaysmito101** [comment]
@ShahJugalR thanks! Now something I want to say. There is a small bug which causes problems in connecting to the local server I will fix it soon. And just if you have any more error a good debugging tip is just google the error code output as winsock error 10038 an d it will give you more detail.

**Comment by ShahJugalR** [comment]
Ok

**Comment by Jaysmito101** [comment]
@ShahJugalR  I tested the code again and it works fine for me.

Here is the code i tested with:

https://pastebin.com/Muix2TZi Client
https://pastebin.com/Gfaf5nx6 Server

**Comment by Jaysmito101** [comment]
If you problem is solved please notify so that i may close this issue.

Happy Coding!

**Comment by ShahJugalR** [comment]
Thats very thankful thing. I check it out asap thanks for your support.
